#!/bin/bash
if [ "$1" = "--README" ]
then
	echo '```'
	echo 'git-commit-all "Commit message here"'
	echo '```'
else
	if [ -z "$1" ]
	then
		echo ' '
		echo 'Usage example : git-commit-all "Commit message here"'
		echo ' '
	else
		git add -A && git commit -a -m "$1"
	fi
fi
