#!/bin/bash
if [ -z "$1" ] || [ -z "$2" ]
then
	echo ' '
	echo 'Usage example : git-author "Firstname Lastname" "firstname.lastname@example.com"'
	echo ' '
else
	git config --global user.name "$1"
	git config --global user.email "$2"
	echo ' '
	echo 'Changed author. The current git author information is is:'
	git config user.name && git config user.email
	echo ' '
fi
