#!/bin/bash
if [ "$1" == "--README" ]
then
	echo 'git-push <branch name> <origin name>'
	echo '```'
	echo 'git-push master'
	echo 'git-push master origin'
	echo '```'
else
	if [ -z "$1" ]
	then
		echo ' '
		echo 'Usage example : git-push <branch name> <origin name>'
		echo 'Usage example : git-push <branch name>'
		echo ' '
	else
		if [ -z "$2" ]
		then
			git push origin $1
		else
			git push $2 $1
		fi
	fi
fi
