#!/bin/bash
readmefile=README.md
basetext=$(cat README-base)
echo "$basetext" > $readmefile

# All references
for file in linux/git-*
do
    if [[ -f $file ]]; then
        output="$($file '--README')"
	somefile="$file"
	somefile=${somefile:2}
	echo "## $somefile" >> $readmefile
	echo "$output" >> $readmefile
    fi
done
