#!/bin/bash

if [ "$1" == '--README' ]
then
	echo 'Push commands using branch and origin names'
	echo '```'
	echo 'git-push master'
	echo 'git-push master origin'
	echo '```'
else
	if [ -z "$1" ]
	then
		echo ' '
		echo 'Usage example : git-push <branch name> <origin name>'
		echo 'Usage example : git-push <branch name>'
		echo 'Default usage example : git-push master'
		echo ' '
	else
		if [ -z "$2" ]
		then
			git push origin $1
		else
			git push $2 $1
		fi
	fi
fi
